// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umrvdvmficxunvujisuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtcnZkdm1maWN4dW52dWppc3VmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNDgzNzEsImV4cCI6MjA2MTgyNDM3MX0.B2YtzNuC4hZDrcwU3bEk1qbaPPb-ji8YQMOWesmnjz4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);